databases:
  - name: rh_db
    databaseName: rh_db
    user: rh_user

services:
  - type: web
    name: rh-numerique
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: rh_db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: rh_db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: rh_db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: rh_db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: rh_db
          property: password
